---
- name: Ensure sudo is installed, fail if not (FreeBSD host)
  when: ansible_os_family == "FreeBSD"
  ansible.builtin.command:
    cmd: which sudo
  changed_when: false

- name: Determine the administrative group
  ansible.builtin.shell: |
    if getent group sudo >/dev/null; then
      echo "sudo";
    elif getent group wheel >/dev/null; then
      echo "wheel";
    else
      echo "unknown";
    fi
  register: admin_group_result
  changed_when: false

- name: Fail if no administrative group is found
  when: admin_group_result.stdout == "unknown"
  ansible.builtin.fail:
    msg: "Neither 'sudo' nor 'wheel' group exists on the system."

- name: Ensure sudo config file exists
  ansible.builtin.command:
    cmd: "ls /etc/sudoers >/dev/null && echo 'File already exists' || touch /etc/sudoers"
  register: touch_sudoers_file_result
  changed_when: "'File already exists' not in touch_sudoers_file_result.stdout"
  become: true

- name: Determine file owner group
  ansible.builtin.shell:
    cmd: "ls -l /etc/sudoers | awk '{print $4}'"
  register: file_owner_group_result
  changed_when: false

- name: Ensure sudo config file on host is updated
  ansible.builtin.template:
    src: ../sudoers.j2
    dest: /etc/sudoers
    owner: root
    group: "{{ file_owner_group_result.stdout }}"
    mode: "0440"
  become: true
  vars:
    admin_username: "{{ lookup('env', 'ADMIN_USERNAME') }}"
