- name: get_base_images | Ensure Ubuntu base IMG file is up to date
  block:
  - name: get_base_images | Ensure Ubuntu ISO files directory exists
    ansible.builtin.file:
      path: /var/lib/libvirt/iso_files/ubuntu
      state: directory
      owner: '{{ ansible_user }}'
      group: '{{ ansible_user }}'
      mode: '0755'

  - name: get_base_images | Determine if Ubuntu base IMG file exists
    ansible.builtin.stat:
      path: /var/lib/libvirt/iso_files/ubuntu/noble-server-cloudimg-amd64.img
    register: ubuntu_base_img

  - name: get_base_images | Set fact if Ubuntu base IMG file is older than 24h
    set_fact:
      ubuntu_img_too_old: "{{ (ansible_date_time.epoch | int) - (ubuntu_base_img.stat.mtime | default(0)) > 86400 }}"
    when: ubuntu_base_img.stat.exists

  - name: get_base_images | Delete Ubuntu base IMG file if it is older than 24h
    when: ubuntu_base_img.stat.exists and ubuntu_img_too_old
    ansible.builtin.file:
      path: /var/lib/libvirt/iso_files/ubuntu/noble-server-cloudimg-amd64.img
      state: absent

  - name: get_base_images | Download Ubuntu base IMG file
    when: ubuntu_base_img.stat.exists == false or ubuntu_img_too_old
    ansible.builtin.get_url:
      url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
      dest: /var/lib/libvirt/iso_files/ubuntu/noble-server-cloudimg-amd64.img
      mode: '0644'
    register: download_ubuntu_img

  - name: get_base_images | Set ubuntu_base_image_changed fact
    ansible.builtin.set_fact:
      ubuntu_base_image_changed: '{{ download_ubuntu_img.changed | default(false) }}'

- name: get_base_images | Ensure Arch base IMG file is up to date
  block:
  - name: get_base_images | Ensure Arch ISO files directory exists
    ansible.builtin.file:
      path: /var/lib/libvirt/iso_files/arch
      state: directory
      owner: '{{ ansible_user }}'
      group: '{{ ansible_user }}'
      mode: '0755'

  - name: get_base_images | Determine if Arch base IMG file exists
    ansible.builtin.stat:
      path: /var/lib/libvirt/iso_files/arch/Arch-Linux-x86_64-cloudimg.qcow2
    register: arch_base_img

  - name: get_base_images | Set fact if Arch base IMG file is older than 24h
    set_fact:
      arch_img_too_old: "{{ (ansible_date_time.epoch | int) - (arch_base_img.stat.mtime | default(0)) > 86400 }}"
    when: arch_base_img.stat.exists

  - name: get_base_images | Delete Arch base IMG file if it is older than 24h
    when: arch_base_img.stat.exists and arch_img_too_old
    ansible.builtin.file:
      path: /var/lib/libvirt/iso_files/arch/Arch-Linux-x86_64-cloudimg.qcow2
      state: absent

  - name: get_base_images | Download Arch base IMG file
    when: arch_base_img.stat.exists == false or arch_img_too_old
    ansible.builtin.get_url:
      url: https://geo.mirror.pkgbuild.com/images/latest/Arch-Linux-x86_64-cloudimg.qcow2
      dest: /var/lib/libvirt/iso_files/arch/Arch-Linux-x86_64-cloudimg.qcow2
      mode: '0644'
    register: download_arch_img

  - name: get_base_images | Set arch_base_image_changed fact
    ansible.builtin.set_fact:
      arch_base_image_changed: '{{ download_arch_img.changed | default(false) }}'

- name: get_base_images | Ensure FreeBSD base IMG file is up to date
  block:
  - name: get_base_images | Ensure FreeBSD ISO files directory exists
    ansible.builtin.file:
      path: /var/lib/libvirt/iso_files/freebsd
      state: directory
      owner: '{{ ansible_user }}'
      group: '{{ ansible_user }}'
      mode: '0755'

  - name: get_base_images | Determine if FreeBSD base IMG file exists
    ansible.builtin.stat:
      path: /var/lib/libvirt/iso_files/freebsd/freebsd-14.2-zfs-2024-12-08.qcow2
    register: freebsd_base_img

  - name: get_base_images | Download FreeBSD base IMG file
    when: freebsd_base_img.stat.exists == false
    ansible.builtin.get_url:
      url: https://object-storage.public.mtl1.vexxhost.net/swift/v1/1dbafeefbd4f4c80864414a441e72dd2/bsd-cloud-image.org/images/freebsd/14.2/2024-12-08/zfs/freebsd-14.2-zfs-2024-12-08.qcow2
      dest: /var/lib/libvirt/iso_files/freebsd/freebsd-14.2-zfs-2024-12-08.qcow2
      mode: '0644'
      timeout: 30
    register: download_freebsd_img

  - name: get_base_images | Set freebsd_base_image_changed fact
    ansible.builtin.set_fact:
      freebsd_base_image_changed: '{{ download_freebsd_img.changed | default(false) }}'
