- name: Destroy VM
  ansible.builtin.command:
    cmd: virsh destroy {{ vm_name }}
  ignore_errors: true
  changed_when: true

- name: Undefine VM
  ansible.builtin.command:
    cmd: virsh undefine {{ vm_name }}
  ignore_errors: true
  changed_when: true

- name: Delete VM disk
  ansible.builtin.command:
    cmd: rm -rf /var/lib/libvirt/images/{{ vm_name }}
  ignore_errors: true
  changed_when: true
  become: true

- name: Forget VM
  ansible.builtin.command:
    cmd: ssh-keygen -f '~/.ssh/known_hosts' -R '{{ hostvars[vm_name].ansible_host }}'
  ignore_errors: true
  changed_when: true
