---
- name: Configure KVM
  hosts: vm_hosts
  gather_facts: true
  environment:
    LIBVIRT_DEFAULT_URI: qemu:///system

  # --- TASKS ---
  tasks:
  - name: Ensure KVM configuration is up to date
    include_role:
      name: configure_kvm

  - name: Ensure base IMG files are up to date
    ansible.builtin.include_role:
      name: install_vm
      tasks_from: get_base_images

  - name: Fail if [OS]_base_image_changed is not set
    ansible.builtin.assert:
      that:
      - ubuntu_base_image_changed is defined
      - arch_base_image_changed is defined
      fail_msg: '[OS]_base_image_changed was not set by generate_images/[OS].yml'

  - name: Ensure VM guests are installed
    include_role:
      name: install_vm
    vars:
      vm_name: '{{ item }}'
    loop: '{{ groups["hosted_on_" + inventory_hostname] }}'
