---
- name: Configure KVM
  hosts: vm_hosts
  gather_facts: true
  environment:
    LIBVIRT_DEFAULT_URI: qemu:///system

  # --- TASKS ---
  tasks:
  - name: Ensure KVM configuration is up to date
    include_role:
      name: configure_kvm

  - name: Ensure VM guests are installed
    include_role:
      name: install_vm
