---
- name: Reset system
  hosts: vm_hosts
  gather_facts: true

  # --- TASKS ---
  tasks:
  - name: Ensure system is unmodified
    include_role:
      name: reset_vm
    vars:
      vm_name: "{{ item }}"
    loop:
      - ubuntu_server_1

- name: Deploy website
  hosts: ubuntu_server_1
  gather_facts: true

  # --- TASKS ---
  tasks:
  - name: Deploy the website onto the server
    include_role:
      name: deploy_website
      tasks_from: old_website
