---
- name: Update system
  hosts: vm_hosts
  gather_facts: true

  # --- TASKS ---
  tasks:
  - name: Ensure system is up to date
    include_role:
      name: reset_vm
    vars:
      vm_name: "{{ item }}"
    loop:
      - ubuntu_server_1
      - ubuntu_server_2
      - ubuntu_server_3
      - ubuntu_server_4
      - freebsd_server_1
      - freebsd_server_2
      - freebsd_server_3
      - freebsd_server_4
