---
- name: Restart SSH server
  block:
  - name: Restart SSH server on Linux systems
    when: ansible_os_family == "Debian" or ansible_os_family == "Archlinux"
    ansible.builtin.systemd_service:
      name: >-
        {{ {
          'Archlinux': 'sshd',
          'Debian': 'ssh'
        }[ansible_os_family] }}
      state: restarted
    become: true
    listen: Restart SSH server

  - name: Restart SSH server on FreeBSD systems
    when: ansible_os_family == "FreeBSD"
    ansible.builtin.command:
      cmd: service sshd restart
    become: true
    changed_when: true
    listen: Restart SSH server

  - name: Wait for the host to be reachable on SSH
    ansible.builtin.wait_for_connection:
      delay: 2
      timeout: 120
    listen: Restart SSH server
