---
- name: Fail if vm is not defined
  ansible.builtin.assert:
    that: vm_name is defined
    fail_msg: 'vm_name was not set'

- name: Ensure base IMG files are up to date
  ansible.builtin.include_role:
    name: install_vm
    tasks_from: get_base_images

- name: Fail if [OS]_base_image_changed is not set
  ansible.builtin.assert:
    that:
    - ubuntu_base_image_changed is defined
    - arch_base_image_changed is defined
    - freebsd_base_image_changed is defined
    fail_msg: '[OS]_base_image_changed was not set by generate_images/[OS].yml'

- name: Ensure VM guest is wiped
  include_role:
    name: reset_vm
    tasks_from: wipe_vm

- name: Ensure VM guest is installed
  include_role:
    name: install_vm
