- name: Destroy VM
  ansible.builtin.command:
    cmd: virsh destroy {{ vm_name }}
  ignore_errors: true
  changed_when: true
  become: true

- name: Undefine VM
  ansible.builtin.command:
    cmd: virsh undefine {{ vm_name }}
  ignore_errors: true
  become: true
  changed_when: true

- name: Delete VM disk
  ansible.builtin.file:
    path: /var/lib/libvirt/images/{{ vm_name }}.qcow2
    state: absent
  become: true

- name: Make Ansible control node forget VM SSH host key
  ansible.builtin.command:
    cmd: ssh-keygen -f "{{ lookup('env', 'HOME') }}/.ssh/known_hosts" -R "{{ hostvars[vm_name].ansible_host }}"
  delegate_to: localhost
  ignore_errors: true
  changed_when: true
